version: "3.8"
services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    container_name: unique_login_system_bff_api
    command: yarn dev:docker
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - unique_login_system_bff_network
    env_file:
      - .env.docker
    volumes:
      - ./:/app/
      - nodemodules:/app/node_modules

volumes:
  nodemodules:

networks:
  unique_login_system_bff_network:
    driver: bridge
